#!/bin/bash


if [ $1 == "configure" ]; then

    chmod 664 /etc/default/vnc-autores

    grep -q ^uinput$ /etc/modules || echo uinput >> /etc/modules

    reload -q vnc-server 2>/dev/null|| :

fi

exit 0
